"""Historical and calculated facts about an age, used to build birthday messages.

Historical facts only use well-known people, and every one is tied to something that really happened at that
age (records, events, deaths...). Where the sources are disputed the text says so ("según la leyenda"...).
Each historical fact comes with a short joke about it, so the message can be: fact + joke.
Keep facts <= MAX_FACT_LENGTH and jokes <= MAX_JOKE_LENGTH so that intro + fact + joke fits Telegram's
256-character copy button.
"""
import random

from i18n import DEFAULT_LANGUAGE

MAX_FACT_LENGTH = 150
MAX_JOKE_LENGTH = 70

# (min_age, max_age, fact_es, fact_en, joke_es, joke_en). {age} is replaced by the age.
FACTS = [
    (2, 3,
     'Con {age} años tienes lo que dura un viaje de ida y vuelta a Marte con las misiones que se planean (2-3 años).',
     "At {age} you're the age a round trip to Mars would take with the missions being planned (2-3 years).",
     'Haz las maletas... pero después de la tarta.',
     'Pack your bags... after the cake.'),
    (4, 4,
     'Cuatro años son un ciclo olímpico completo.',
     'Four years is one full Olympic cycle.',
     'Los Juegos son cada cuatro años; tu tarta, cada año.',
     'The Olympics come every four years; your cake, every year.'),
    (10, 10,
     '¡Una década entera de vida!',
     'A whole decade of life!',
     'Y todavía sin hipoteca.',
     'And still no mortgage.'),
    (12, 12,
     'Doce años son un ciclo completo del zodiaco chino: ya has pasado por todos los animales.',
     "Twelve years is a full Chinese zodiac cycle: you've been through every animal.",
     'Ojalá te haya tocado un animal simpático.',
     'Hopefully you got a friendly animal.'),
    (18, 18,
     'Con 18 años se alcanza la mayoría de edad en muchos países.',
     'At 18 you reach adulthood in many countries.',
     'Ya puedes votar... y seguir pidiendo tarta.',
     'You can vote now... and still ask for cake.'),
    (20, 20,
     '¡Dos décadas ya!',
     'Two decades already!',
     'Ya no eres adolescente, lo sentimos.',
     'No longer a teenager, sorry.'),
    (25, 25,
     '¡Un cuarto de siglo!',
     'A quarter of a century!',
     'Un cuarto de siglo y aún sin saber qué ser de mayor.',
     'A quarter century and still deciding what to be.'),
    (30, 120,
     'Ya tienes más años que el perro más longevo registrado: Bluey, un pastor australiano que vivió 29 años y 5 meses.',
     "You're older than the longest-lived dog on record: Bluey, an Australian cattle dog who lived 29 years and 5 months.",
     'Y a ti nadie te saca a pasear... ¡salvo hoy!',
     'And nobody takes you for a walk... except today!'),
    (39, 120,
     'Eres mayor que el gato más longevo registrado, Creme Puff, que llegó a los 38 años.',
     "You're older than the longest-lived cat on record, Creme Puff, who reached 38.",
     'Los gatos tienen siete vidas; tú una: ¡aprovéchala!',
     'Cats have nine lives; you have one. Make it count!'),
    (42, 42,
     '42 es la respuesta a la vida, el universo y todo lo demás en «La guía del autoestopista galáctico».',
     "42 is the answer to life, the universe and everything in «The Hitchhiker's Guide to the Galaxy».",
     'Y no hizo falta un ordenador del tamaño de un planeta.',
     'And no planet-sized computer was needed.'),
    (50, 50,
     '¡Medio siglo!',
     'Half a century!',
     'Ya puedes decir «en mis tiempos» con autoridad.',
     'You can now say «back in my day» with authority.'),
    (64, 64,
     "Ya tienes la edad de la canción de los Beatles «When I'm Sixty-Four».",
     "You're the age of the Beatles song «When I'm Sixty-Four».",
     '¿Me seguirás necesitando? Claro, hay tarta.',
     "Will you still need me? Of course, there's cake."),
    (75, 75,
     '¡Tres cuartos de siglo!',
     'Three quarters of a century!',
     'Y aún te quedan cuartos por estrenar.',
     'And you still have quarters left to spend.'),
    (100, 120,
     '¡Un siglo entero! Tu cumpleaños es de los que salen en las noticias.',
     'A whole century! Your birthday is one that makes the news.',
     'Ya eres más antiguo que la mayoría de memes.',
     "You're older than most memes."),
    (1, 1,
     'Bruce Lee debutó en el cine siendo un bebé de unos meses.',
     'Bruce Lee made his film debut as a baby of a few months.',
     'Seguro que ya daba patadas desde la cuna.',
     'Probably already kicking from the crib.'),
    (2, 2,
     'Con 2 años y 10 meses, Pu Yi fue coronado como el último emperador de China.',
     'At 2 years and 10 months, Puyi was crowned the last emperor of China.',
     'A ti solo te coronamos con un gorro de fiesta.',
     "We'll only crown you with a party hat."),
    (3, 3,
     'A los 3 años, Louis Braille se clavó una lezna en el ojo en el taller de su padre y perdió la vista. Luego inventó el braille.',
     "At 3, Louis Braille stabbed his eye with an awl in his father's workshop and lost his sight. Later he invented braille.",
     'Por suerte hoy lo más punzante es la vela.',
     'Luckily, today the sharpest thing is the candle.'),
    (4, 4,
     'A los 4 años, el 14.º Dalai Lama fue entronizado en el Tíbet.',
     'At 4, the 14th Dalai Lama was enthroned in Tibet.',
     'Tú, de momento, reinas en tu cuarto.',
     'You, for now, rule your own room.'),
    (4, 4,
     'Con 4 años, Luis XIV se convirtió en rey de Francia. Reinaría 72 años.',
     'At 4, Louis XIV became king of France. He would reign for 72 years.',
     'Y tú reinas sobre la tarta.',
     'And you rule over the cake.'),
    (5, 5,
     'A los 5 años, Mozart ya componía sus primeras piezas de música.',
     'At 5, Mozart was already composing his first pieces.',
     'Tú compones garabatos. ¡Y son geniales!',
     "You compose doodles. And they're great!"),
    (6, 6,
     'A los 6 años, Mozart tocó ante la emperatriz de Austria y, según la anécdota, pidió matrimonio a la futura María Antonieta.',
     'At 6, Mozart played for the Empress of Austria and, the story goes, proposed to the future Marie Antoinette.',
     'Eso sí que es ligar pronto.',
     "Now that's flirting early."),
    (7, 7,
     'A los 7 años, Mozart empezó una gira por Europa tocando ante reyes y emperadores.',
     'At 7, Mozart began a tour of Europe, playing for kings and emperors.',
     'Y sin pagar exceso de equipaje.',
     'And without paying for extra baggage.'),
    (8, 8,
     'A los 8 años, Picasso pintó «El picador», su primer óleo conocido.',
     'At 8, Picasso painted «The Picador», his first known oil painting.',
     'A esa edad los demás dibujábamos soles con cara.',
     'At that age the rest of us drew smiling suns.'),
    (9, 9,
     'Con unos 9 años, Tutankamón ya era faraón de Egipto.',
     'At around 9, Tutankhamun was already pharaoh of Egypt.',
     'Tú, a esa edad, solo mandabas en la consola.',
     'At that age you only ruled the game console.'),
    (9, 9,
     'A los 9 años, Pedro el Grande presenció cómo los streltsy asesinaban a sus familiares en el Kremlin.',
     'At 9, Peter the Great watched the streltsy murder his relatives in the Kremlin.',
     'Menuda infancia. Mejor una tarta.',
     'What a childhood. Cake is better.'),
    (10, 10,
     'A los 10 años le diagnosticaron a Lionel Messi un déficit de hormona del crecimiento que casi frena su carrera.',
     'At 10, Lionel Messi was diagnosed with a growth hormone deficiency that nearly stopped his career.',
     'Y míralo ahora: nada lo ha frenado.',
     'And look at him now: nothing stopped him.'),
    (11, 11,
     'A los 11 años, Mozart pasó la viruela y estuvo varios días ciego.',
     'At 11, Mozart caught smallpox and was blind for several days.',
     'Ciego y todo, siguió. Tú, sin postre, ni hablar.',
     "Even blind, he carried on. You'll get dessert."),
    (12, 12,
     'A los 12 años, Beethoven publicó su primera obra: unas variaciones para piano.',
     'At 12, Beethoven published his first work: a set of piano variations.',
     'A esa edad los demás publicábamos trabajos del cole.',
     'At that age the rest of us turned in school projects.'),
    (13, 13,
     'El día que cumplió 13 años, Ana Frank recibió el diario donde contaría su vida escondida de los nazis.',
     'On her 13th birthday, Anne Frank received the diary where she would tell of her life hiding from the Nazis.',
     'Un diario puede cambiar el mundo. ¡Escribe el tuyo!',
     'A diary can change the world. Write yours!'),
    (13, 13,
     'A los 13 años, Messi firmó su primer contrato con el Barcelona... en una servilleta.',
     'At 13, Messi signed his first Barcelona contract... on a napkin.',
     'Nunca subestimes una servilleta.',
     'Never underestimate a napkin.'),
    (13, 13,
     'Juana de Arco dijo oír por primera vez las voces de los santos cuando tenía 13 años.',
     'Joan of Arc said she first heard the voices of saints when she was 13.',
     'Hoy las voces solo preguntan quién se come la tarta.',
     "Nowadays the voices just ask who's eating the cake."),
    (13, 13,
     'Según ella, con 13 años Jeanne Calment conoció a Van Gogh: dijo que era feo, sucio y olía a alcohol.',
     'At 13, Jeanne Calment said she met Van Gogh: ugly, dirty and smelling of alcohol.',
     'Vivió 122 años: con ese carácter, normal.',
     'She lived to 122 - with that attitude, no wonder.'),
    (14, 14,
     'María Antonieta se casó con 14 años con Luis XVI, un matrimonio que tardó siete años en consumarse.',
     'Marie Antoinette married Louis XVI at 14, a marriage that took seven years to be consummated.',
     'Tranquilo: tu fiesta no tardará siete años.',
     "Don't worry, your party won't take seven years."),
    (15, 15,
     'A los 15 años, Louis Braille perfeccionó el alfabeto que aún usan las personas ciegas de todo el mundo.',
     'At 15, Louis Braille perfected the alphabet blind people still use all over the world.',
     'Hay quien a los 15 aún no ha hecho la cama.',
     "Some 15-year-olds still haven't made their bed."),
    (16, 16,
     'A los 16 años, Iván IV se coronó como el primer zar de Rusia.',
     'At 16, Ivan IV crowned himself the first tsar of Russia.',
     'A los 16 tú sacabas el carné. Él, un país.',
     'At 16 you got a license. He got a country.'),
    (16, 16,
     'Nerón fue proclamado emperador de Roma con 16 años.',
     'Nero was proclaimed emperor of Rome at 16.',
     'Que tu único imperio sea el de la nevera.',
     'May your only empire be the fridge.'),
    (16, 16,
     'A los 16 años, Alejandro Magno gobernaba Macedonia en ausencia de su padre y sofocó una rebelión.',
     "At 16, Alexander the Great ruled Macedonia in his father's absence and crushed a rebellion.",
     'Y tú, a duras penas, mandabas en casa.',
     'And you barely ruled the house.'),
    (17, 17,
     'A los 17 años, Juana de Arco lideró un ejército y levantó el asedio de Orleans.',
     'At 17, Joan of Arc led an army and lifted the siege of Orléans.',
     'Tú, como mucho, liberas el último trozo de tarta.',
     "You'd at most liberate the last slice of cake."),
    (17, 17,
     'Con 17 años, Pelé ganó el Mundial de 1958 y marcó dos goles en la final.',
     'At 17, Pelé won the 1958 World Cup and scored twice in the final.',
     'Tú, a los 17, como mucho ganabas al parchís.',
     'At 17 the best you won was a board game.'),
    (17, 17,
     'Según Tácito y Suetonio, con 17 años Nerón hizo envenenar en plena cena a su hermanastro Británico.',
     'According to Tacitus and Suetonius, at 17 Nero had his stepbrother Britannicus poisoned at dinner.',
     'Hoy mejor evita las cenas con hermanastros.',
     'Maybe skip dinner with stepbrothers today.'),
    (18, 18,
     'A los 18 años, Mary Shelley empezó a escribir «Frankenstein» durante unas vacaciones lluviosas junto al lago Lemán.',
     'At 18, Mary Shelley began writing «Frankenstein» during a rainy holiday by Lake Geneva.',
     'Tú, a los 18, escribías... mensajes de WhatsApp.',
     'At 18 you were writing... text messages.'),
    (18, 18,
     'Cleopatra ya reinaba en Egipto con 18 años.',
     'Cleopatra was already ruling Egypt at 18.',
     'Hoy la reina o el rey del día eres tú.',
     "Today you're the queen or king of the day."),
    (19, 19,
     'Juana de Arco murió quemada viva en Ruan con 19 años.',
     'Joan of Arc was burned alive in Rouen at 19.',
     'Por suerte hoy lo único que arde son las velas.',
     'Luckily, today only the candles are burning.'),
    (19, 19,
     'Con 19 años, Mark Zuckerberg lanzó Facebook desde su habitación de Harvard.',
     'At 19, Mark Zuckerberg launched Facebook from his Harvard dorm room.',
     '¿Y tú qué creaste a los 19? ¿Una playlist?',
     'And what did you create at 19? A playlist?'),
    (19, 19,
     'Con 19 años, Bill Gates fundó Microsoft tras dejar Harvard.',
     'At 19, Bill Gates founded Microsoft after dropping out of Harvard.',
     'Dejó los estudios y no le fue mal.',
     'He dropped out and it worked out fine.'),
    (20, 20,
     'Alejandro Magno heredó el trono de Macedonia con 20 años, tras el asesinato de su padre.',
     'Alexander the Great inherited the throne of Macedonia at 20, after his father was murdered.',
     'Tu herencia de hoy: una tarta.',
     'Your inheritance today: a cake.'),
    (20, 20,
     'A los 20 años, Mary Shelley publicó «Frankenstein» de forma anónima.',
     'At 20, Mary Shelley published «Frankenstein» anonymously.',
     'Un éxito monstruoso, y sin poner su nombre.',
     'A monstrous success, and without her name on it.'),
    (21, 21,
     'Con 21 años, Nerón mandó matar a su madre, Agripina, tras fracasar un intento con un barco trampa.',
     'At 21, Nero had his mother, Agrippina, killed after a first attempt with a booby-trapped boat failed.',
     'Llama a tu madre, pero no la invites a un barco.',
     "Call your mother - just don't invite her on a boat."),
    (21, 21,
     'Con 21 años, Steve Jobs fundó Apple con Wozniak en el garaje de sus padres.',
     "At 21, Steve Jobs founded Apple with Wozniak in his parents' garage.",
     'Tu garaje sirve para una fiesta... o para una empresa.',
     'Your garage works for a party... or a company.'),
    (22, 22,
     'A los 22 años, Cleopatra tuvo un hijo con Julio César.',
     'At 22, Cleopatra had a son with Julius Caesar.',
     'Tú, a los 22, aún buscabas piso.',
     'At 22 you were still looking for an apartment.'),
    (23, 23,
     'Con 23 años, Bonnie Parker cayó junto a Clyde Barrow en una emboscada policial en Luisiana.',
     'At 23, Bonnie Parker was gunned down with Clyde Barrow in a police ambush in Louisiana.',
     'Nada como una buena huida. Hoy, de la dieta.',
     'Nothing like a getaway. Today, from your diet.'),
    (23, 23,
     'A los 23 años, Isaac Newton sentó las bases del cálculo y la gravedad, encerrado en casa por la peste.',
     'At 23, Isaac Newton laid the foundations of calculus and gravity, stuck at home because of the plague.',
     'Encerrado en casa, como tú con las series.',
     'Stuck at home, just like you with your series.'),
    (24, 24,
     'A los 24 años, Lee Harvey Oswald disparó a Kennedy y fue asesinado a tiros en directo por televisión dos días después.',
     'At 24, Lee Harvey Oswald shot Kennedy and was himself shot dead on live TV two days later.',
     'Mejor una fiesta en directo que un directo así.',
     'Better a live party than a live broadcast like that.'),
    (24, 24,
     'Calígula llegó a emperador de Roma con 24 años.',
     'Caligula became emperor of Rome at 24.',
     'Que tu único poder hoy sea elegir la playlist.',
     'May your only power today be picking the playlist.'),
    (24, 24,
     'James Dean murió con 24 años al chocar con su Porsche.',
     'James Dean died at 24 when his Porsche crashed.',
     'Conduce con cuidado, rebelde sin tarta.',
     'Drive safe, rebel without a cake.'),
    (25, 25,
     'Con 25 años, Orson Welles dirigió y protagonizó «Ciudadano Kane».',
     'At 25, Orson Welles directed and starred in «Citizen Kane».',
     'Y tú a los 25 sigues siendo «el nuevo» en la oficina.',
     "And at 25 you're still «the new one» at the office."),
    (26, 26,
     'A los 26 años, John Wilkes Booth disparó a Lincoln y murió doce días después, acorralado en un granero.',
     'At 26, John Wilkes Booth shot Lincoln and died twelve days later, cornered in a barn.',
     'Tranquilo: hoy lo único que disparan son fotos.',
     'Relax: today the only shots are photos.'),
    (26, 26,
     'Con 26 años, Al Capone se convirtió en el jefe de la mafia de Chicago.',
     'At 26, Al Capone became the boss of the Chicago mob.',
     'Hoy el jefe eres tú; el único delito, otro trozo.',
     "Today you're the boss; the only crime is one more slice."),
    (26, 26,
     'Con 26 años, Einstein publicó la relatividad especial mientras trabajaba en una oficina de patentes.',
     'At 26, Einstein published special relativity while working in a patent office.',
     'Todo es relativo, menos la tarta.',
     'Everything is relative, except the cake.'),
    (26, 26,
     'Hacia los 25 años el lóbulo frontal termina de madurar. Así que a tus {age} ya no tienes excusa médica para tomar malas decisiones.',
     'Around 25 the frontal lobe of the human brain finishes maturing. So at {age} you no longer have a medical excuse for bad decisions.',
     'Aun así, hoy te perdonamos la tercera copa.',
     "Still, we'll forgive the third drink today."),
    (27, 27,
     'Tienes la edad del «Club de los 27»: Cobain, Winehouse, Hendrix y Joplin murieron con 27 años. ¡Sobrevive!',
     "You're the age of the «27 Club»: Cobain, Winehouse, Hendrix and Joplin died at 27. Survive!",
     'Hoy la única leyenda que celebramos eres tú.',
     'The only legend we celebrate today is you.'),
    (28, 28,
     'A los 28 años, Dostoievski fue condenado a muerte y, ante el pelotón, le anunciaron el indulto en el último segundo.',
     'At 28, Dostoevsky was sentenced to death and, facing the firing squad, was pardoned at the last second.',
     'El mayor susto que te daremos hoy es la tarta.',
     "The biggest scare we'll give you today is the cake."),
    (28, 28,
     'Calígula fue asesinado a los 28 años por su propia guardia pretoriana.',
     'Caligula was murdered at 28 by his own Praetorian Guard.',
     'Que hoy tu única guardia sea la de la nevera.',
     'May your only guard today be the fridge.'),
    (29, 29,
     'A los 29 años, Alejandro Magno derrotó al rey Poros en la India.',
     'At 29, Alexander the Great defeated King Porus in India.',
     'Y tú aún te pierdes con Google Maps.',
     'And you still get lost with Google Maps.'),
    (30, 30,
     'Nerón murió a los 30 años apuñalándose el cuello mientras llegaban sus enemigos.',
     'Nero died at 30, stabbing himself in the throat as his enemies arrived.',
     'Tú, a los 30, solo apuñalas la tarta.',
     'At 30 you only stab the cake.'),
    (30, 30,
     'A los 30 años, Napoleón dio un golpe de Estado y tomó el poder en Francia.',
     'At 30, Napoleon staged a coup and took power in France.',
     'Hoy tu golpe lo das en la pista de baile.',
     'Today your coup happens on the dance floor.'),
    (31, 31,
     'Mozart estrenó «Don Giovanni» con 31 años.',
     'Mozart premiered «Don Giovanni» at 31.',
     'Tú, a los 31, estrenas... otro año más.',
     "At 31 you're premiering... another year."),
    (32, 32,
     'Alejandro Magno murió con 32 años en Babilonia tras unos días de fiebre. La causa sigue debatida.',
     'Alexander the Great died at 32 in Babylon after days of fever. The cause is still debated.',
     'Mejor que la fiebre de hoy sea la del sábado noche.',
     'Better to have Saturday night fever instead.'),
    (32, 32,
     'Bruce Lee murió con 32 años por un edema cerebral.',
     'Bruce Lee died at 32 of cerebral edema.',
     'Sé agua, amigo... y bebe agua también hoy.',
     'Be water, my friend... and drink some water today.'),
    (32, 32,
     'A los 32 años, Al Capone fue condenado por evasión de impuestos, no por sus crímenes.',
     'At 32, Al Capone was convicted of tax evasion, not for his crimes.',
     'Declara todos tus regalos a Hacienda.',
     'Declare all your gifts to the tax office.'),
    (33, 33,
     'Eva Perón murió con 33 años; su cuerpo embalsamado desapareció durante 16 años.',
     'Eva Perón died at 33; her embalmed body vanished for 16 years.',
     'Hoy lo único desaparecido es el último trozo de tarta.',
     'Today the only thing missing is the last slice of cake.'),
    (33, 33,
     'Según la tradición cristiana, Jesús murió crucificado con 33 años.',
     'According to Christian tradition, Jesus died crucified at 33.',
     'Hoy que solo te traicione la báscula.',
     'Today may only your scale betray you.'),
    (34, 34,
     'Jesse James murió con 34 años, tiroteado por la espalda por un compañero de su banda mientras colgaba un cuadro.',
     'Jesse James died at 34, shot in the back by a member of his own gang while hanging a picture.',
     'Nunca cuelgues cuadros delante de amigos sospechosos.',
     'Never hang pictures in front of shady friends.'),
    (34, 34,
     'Ayrton Senna murió con 34 años en un accidente en la curva de Tamburello, en Imola.',
     'Ayrton Senna died at 34 in a crash at the Tamburello corner in Imola.',
     'Hoy, curva de la tarta: frena con cuidado.',
     'Watch out for the cake corner today.'),
    (35, 35,
     'Mozart murió con 35 años, enfermo y sin dinero, y lo enterraron en una tumba común.',
     'Mozart died at 35, sick and penniless, and was buried in a common grave.',
     'Qué legado dejó. Tú dejas fiesta.',
     'What a legacy. You leave a party.'),
    (35, 35,
     'Guy Fawkes se lanzó de la escalera con 35 años para romperse el cuello y evitar el descuartizamiento.',
     'Guy Fawkes leapt from the ladder at 35 to break his neck and avoid being quartered.',
     'Hoy el único explosivo es la bengala de la tarta.',
     'Today the only explosive is the cake sparkler.'),
    (35, 35,
     'A los 35 años, Van Gogh se cortó parte de la oreja izquierda y se la entregó a una mujer en un burdel.',
     'At 35, Van Gogh cut off part of his left ear and gave it to a woman at a brothel.',
     'Quédate con las dos orejas para oír felicitaciones.',
     'Keep both ears to hear the congratulations.'),
    (35, 35,
     'Martin Luther King ganó el Nobel de la Paz con 35 años, el más joven hasta entonces.',
     'Martin Luther King won the Nobel Peace Prize at 35, the youngest to that date.',
     'Tú, a los 35, con suerte ganas el bingo.',
     'At 35 you might, with luck, win bingo.'),
    (36, 36,
     'Bob Marley murió con 36 años de un melanoma que empezó en un dedo del pie.',
     'Bob Marley died at 36 of a melanoma that started in a toe.',
     'Hoy: «no woman, no cry». A celebrar.',
     "Today: «no woman, no cry». Let's celebrate."),
    (37, 37,
     'María Antonieta fue guillotinada con 37 años; pisó al verdugo y le pidió disculpas: «No lo he hecho a propósito».',
     "Marie Antoinette was guillotined at 37; she stepped on the executioner's foot and said: «Pardon me, I did not do it on purpose».",
     'Dicen que dijo «que coman pasteles». Hoy sí.',
     'They say she said «let them eat cake». Today, we do.'),
    (38, 38,
     'Luis XVI fue guillotinado con 38 años.',
     'Louis XVI was guillotined at 38.',
     'Mejor perder solo un trozo de tarta.',
     'Better to lose just a slice of cake.'),
    (38, 38,
     'Federico García Lorca fue fusilado con 38 años y su cuerpo nunca apareció.',
     'Federico García Lorca was shot at 38 and his body was never found.',
     'La poesía se queda; la tarta no: ¡a soplar!',
     "The poetry stays; the cake won't: blow out the candles!"),
    (38, 38,
     'Barbanegra murió con unos 38 años: cinco disparos y veinte cortes de espada, y su cabeza colgó de su barco.',
     'Blackbeard died at about 38: five gunshots and twenty sword cuts, and his head hung from his ship.',
     'Hoy tu tesoro son los regalos.',
     'Today your treasure is the gifts.'),
    (39, 39,
     'Chopin murió con 39 años y pidió que le abrieran el pecho para no ser enterrado vivo. Su corazón está en Varsovia.',
     "Chopin died at 39 and asked to be cut open so he wouldn't be buried alive. His heart is in Warsaw.",
     'Pide siempre segunda opinión... y segundo trozo.',
     'Always get a second opinion... and a second slice.'),
    (39, 39,
     'Che Guevara fue capturado y ejecutado con 39 años, y le cortaron las manos para identificarlo.',
     'Che Guevara was captured and executed at 39, and his hands were cut off to identify him.',
     'Hoy nadie te quita las manos de la tarta.',
     'Nobody takes your hands off the cake today.'),
    (39, 39,
     'Según la tradición, Cleopatra murió con 39 años por la mordedura de una serpiente venenosa.',
     'According to tradition, Cleopatra died at 39 from the bite of a venomous snake.',
     'Tu único veneno hoy: demasiado azúcar.',
     'Your only poison today: too much sugar.'),
    (40, 40,
     'Edgar Allan Poe murió con 40 años, tras aparecer delirando en Baltimore con ropa que no era suya.',
     "Edgar Allan Poe died at 40, after turning up delirious in Baltimore in clothes that weren't his.",
     'No salgas con ropa ajena... salvo que sea un disfraz.',
     "Don't go out in someone else's clothes... unless it's a costume."),
    (41, 41,
     'Mata Hari fue fusilada con 41 años. Se dice que se negó a llevar los ojos vendados.',
     'Mata Hari was shot at 41. It is said she refused to wear a blindfold.',
     'Hoy lo único que se dispara son los corchos.',
     'Today the only shots are champagne corks.'),
    (41, 41,
     'A los 41 años, Houdini casi muere asfixiado durante una prueba en la que se hizo enterrar vivo.',
     'At 41, Houdini nearly suffocated during a stunt in which he had himself buried alive.',
     'Si la fiesta te encierra, escapa como él.',
     'If the party locks you in, escape like him.'),
    (42, 42,
     'Elvis Presley murió con 42 años y lo encontraron boca abajo en el suelo de su cuarto de baño.',
     'Elvis Presley died at 42 and was found face down on his bathroom floor.',
     'Hoy el rey eres tú. ¡Elvis vive... en la pista!',
     "Today you're the king. Elvis lives... on the dance floor!"),
    (42, 42,
     'Con 42 años, Theodore Roosevelt se convirtió en el presidente más joven de EE. UU. tras el asesinato de McKinley.',
     "At 42, Theodore Roosevelt became the youngest US president after McKinley's assassination.",
     'Y tú, presidente... de la comunidad de vecinos.',
     "And you, president... of the neighbors' association."),
    (43, 43,
     'Kennedy fue el presidente más joven elegido de EE. UU.: 43 años.',
     'Kennedy was the youngest elected US president: 43.',
     'Hoy eres presidente o presidenta de la tarta.',
     "Today you're president of the cake."),
    (44, 44,
     'Pablo Escobar murió con 44 años, tiroteado en un tejado mientras huía descalzo.',
     'Pablo Escobar died at 44, shot on a rooftop while fleeing barefoot.',
     'Tú, descalzo, solo si bailas.',
     "You - barefoot only if you're dancing."),
    (45, 45,
     'Pancho Villa murió con 45 años, acribillado en una emboscada en su coche.',
     'Pancho Villa died at 45, riddled with bullets in an ambush on his car.',
     'Hoy la única emboscada es una fiesta sorpresa.',
     'Today the only ambush is a surprise party.'),
    (45, 45,
     'Vlad el Empalador murió con unos 45 años. Según la tradición, su cabeza fue enviada al sultán conservada en miel.',
     'Vlad the Impaler died at about 45. Tradition says his head was sent to the sultan preserved in honey.',
     'Con la cabeza en miel, al menos era dulce.',
     'Preserved in honey, at least he was sweet.'),
    (45, 45,
     'Ötzi, el hombre de hielo, murió con unos 45 años con una flecha clavada en la espalda.',
     'Ötzi the Iceman died at about 45 with an arrow in his back.',
     'Y tú aún no te has enfriado con los años.',
     "And you haven't frozen up with age."),
    (46, 46,
     'Oscar Wilde murió con 46 años, arruinado y exiliado, en una habitación de hotel de París.',
     'Oscar Wilde died at 46, ruined and in exile, in a Paris hotel room.',
     'Hoy tu frase: «puedo resistirlo todo, menos la tarta».',
     'Your line today: «I can resist everything except cake».'),
    (47, 47,
     'Rasputín murió con 47 años. Según la leyenda, lo envenenaron, le dispararon y lo tiraron a un río, aún con vida.',
     'Rasputin died at 47. Legend says he was poisoned, shot and thrown into a river, still alive.',
     'Si sobrevives a esta fiesta, eres como Rasputín.',
     "If you survive this party, you're Rasputin."),
    (47, 47,
     'Frida Kahlo murió con 47 años, una semana después de su cumpleaños.',
     'Frida Kahlo died at 47, a week after her birthday.',
     '«¿Pies para qué los quiero si tengo alas?» Y tarta.',
     '«Feet, what do I need them for if I have wings to fly?» And cake.'),
    (48, 48,
     'Al Capone murió con 48 años, con la mente arruinada por la sífilis.',
     'Al Capone died at 48, his mind ruined by syphilis.',
     'Mañana sin mala cabeza: celebra hoy sin resacas.',
     'No bad head tomorrow: celebrate without a hangover.'),
    (49, 49,
     'Douglas Adams, el autor de «La guía del autoestopista galáctico», murió con 49 años de un infarto en el gimnasio.',
     "Douglas Adams, author of «The Hitchhiker's Guide to the Galaxy», died at 49 of a heart attack at the gym.",
     'Y no entres en pánico: lleva siempre tu toalla.',
     "And don't panic: always know where your towel is."),
    (50, 50,
     'A los 50 años, Darwin publicó «El origen de las especies».',
     'At 50, Darwin published «On the Origin of Species».',
     'Y aquí seguimos evolucionando, tarta a tarta.',
     'And here we are, evolving one cake at a time.'),
    (51, 51,
     'Napoleón murió con 51 años exiliado en Santa Elena. Se sospecha que fue por un cáncer de estómago o por arsénico.',
     'Napoleon died at 51 in exile on Saint Helena. Stomach cancer or arsenic poisoning are suspected.',
     'Era bajito, como los trozos de tarta.',
     'He was short, like the slices of cake.'),
    (52, 52,
     'Shakespeare murió con 52 años; una leyenda dice que fue tras una noche de mucha bebida.',
     'Shakespeare died at 52; a legend says it followed a night of heavy drinking.',
     'Ser o no ser... el último en irse de la fiesta.',
     'To be or not to be... the last to leave the party.'),
    (52, 52,
     'Houdini murió con 52 años de peritonitis, tras recibir unos puñetazos en el estómago de un estudiante.',
     'Houdini died at 52 of peritonitis, after a student punched him in the stomach.',
     'Hoy evita el boxeo con estudiantes.',
     'Avoid boxing with students today.'),
    (53, 53,
     'Chaikovski murió con 53 años de cólera, según la versión oficial.',
     'Tchaikovsky died at 53 of cholera, according to the official version.',
     'Hoy solo el Cascanueces, y agua hervida.',
     'Only the Nutcracker today, and boiled water.'),
    (54, 54,
     'A los 54 años, Alfred Nobel leyó su propio obituario, publicado por error: «El mercader de la muerte ha muerto».',
     'At 54, Alfred Nobel read his own obituary, published by mistake: «The merchant of death is dead».',
     'Hoy el único premio es el de la tarta.',
     "Today's only prize is the cake."),
    (55, 55,
     'Julio César fue apuñalado 23 veces en el Senado por sus aliados con 55 años.',
     'Julius Caesar was stabbed 23 times in the Senate by his allies at 55.',
     'Cuidado con los idus y con quien pida el último trozo.',
     'Beware the ides, and whoever wants the last slice.'),
    (55, 55,
     'Enrique VIII murió con 55 años, obeso y con una úlcera en la pierna que no cerraba.',
     'Henry VIII died at 55, obese and with a leg ulcer that would not heal.',
     'El banquete es tuyo; la dieta, problema de mañana.',
     "The feast is yours; the diet is tomorrow's problem."),
    (56, 56,
     'Beethoven murió con 56 años, sordo y con el hígado destrozado; en su pelo se hallaron altos niveles de plomo.',
     'Beethoven died at 56, deaf and with a wrecked liver; high levels of lead were found in his hair.',
     'Aun así lo oyó todo. Tú, oye los aplausos.',
     'He heard it all anyway. You, enjoy the applause.'),
    (56, 56,
     'Lincoln fue asesinado con 56 años en un teatro; Booth saltó al escenario gritando «Sic semper tyrannis».',
     'Lincoln was assassinated at 56 in a theater; Booth leapt onto the stage shouting «Sic semper tyrannis».',
     'Hoy la única función es la de tu cumple.',
     'Today the only show is your birthday.'),
    (57, 57,
     'A los 57 años, Cervantes publicó la primera parte de «Don Quijote».',
     'At 57, Cervantes published the first part of «Don Quixote».',
     'Y tú luchando contra molinos... de tareas pendientes.',
     'And you, fighting windmills... of to-dos.'),
    (58, 58,
     "A los 58 años, Ray Kroc compró McDonald's a los hermanos que lo fundaron.",
     "At 58, Ray Kroc bought McDonald's from the brothers who founded it.",
     'Hoy el menú del cumple lo eliges tú.',
     'Today you pick the birthday menu.'),
    (60, 60,
     'A los 60 años, Hitchcock estrenó «Psicosis» y usó sirope de chocolate como sangre.',
     'At 60, Hitchcock released «Psycho» and used chocolate syrup as blood.',
     'Mejor sirope en la tarta que en la ducha.',
     'Better syrup on the cake than in the shower.'),
    (62, 62,
     'Nostradamus murió con 62 años; cuenta la leyenda que predijo el día de su muerte.',
     'Nostradamus died at 62; legend says he predicted the day of his death.',
     'Predicción: hoy habrá tarta.',
     'Prediction: there will be cake today.'),
    (64, 64,
     'Bram Stoker, el creador de Drácula, murió con 64 años.',
     'Bram Stoker, the creator of Dracula, died at 64.',
     'Hoy nada de ajo: ¡a soplar velas!',
     'No garlic today: blow out the candles!'),
    (65, 65,
     'Bach murió con 65 años, poco después de dos operaciones de ojos fallidas.',
     'Bach died at 65, shortly after two failed eye operations.',
     'Hoy suena el «Cumpleaños feliz» en versión Bach.',
     'Today: Happy Birthday, Bach edition.'),
    (66, 66,
     'Marie Curie murió con 66 años de anemia aplásica, tras décadas manipulando radio. Sus cuadernos aún son radiactivos.',
     'Marie Curie died at 66 of aplastic anemia after decades handling radium. Her notebooks are still radioactive.',
     'Hoy lo único radiante es tu sonrisa.',
     'Today the only radiant thing is your smile.'),
    (67, 67,
     'Leonardo da Vinci murió con 67 años en Amboise, Francia.',
     'Leonardo da Vinci died at 67 in Amboise, France.',
     'Otra obra maestra: tu cumpleaños.',
     'Another masterpiece: your birthday.'),
    (68, 68,
     'Cervantes murió con 68 años, en 1616, el mismo año que Shakespeare.',
     'Cervantes died at 68, in 1616, the same year as Shakespeare.',
     'Mismo año que Shakespeare: la literatura se jubiló.',
     'Same year as Shakespeare: literature retired.'),
    (69, 69,
     'A los 69 años, Galileo fue juzgado por la Inquisición y acabó bajo arresto domiciliario.',
     'At 69, Galileo was tried by the Inquisition and ended up under house arrest.',
     'Solo dijo que la Tierra se mueve... como en tu fiesta.',
     'All he said was that the Earth moves... like at your party.'),
    (69, 69,
     'David Bowie murió con 69 años, dos días después de publicar su último disco, «Blackstar».',
     'David Bowie died at 69, two days after releasing his last album, «Blackstar».',
     'Hoy eres tu propio Starman.',
     "Today you're your own Starman."),
    (70, 70,
     'Con 70 años, Benjamin Franklin firmó la Declaración de Independencia.',
     'At 70, Benjamin Franklin signed the Declaration of Independence.',
     'Él firmaba la independencia; tú firmas el postre.',
     'He signed independence; you sign for dessert.'),
    (70, 70,
     'Reagan sobrevivió a un disparo en el pulmón con 70 años y bromeó con los cirujanos: «Espero que sean republicanos».',
     "Reagan survived a bullet in the lung at 70 and joked to the surgeons: «I hope you're all Republicans».",
     'Y tú dramatizas con un simple catarro.',
     'And you make a drama out of a simple cold.'),
    (71, 71,
     'Nelson Mandela salió de prisión con 71 años, tras 27 entre rejas.',
     'Nelson Mandela walked out of prison at 71, after 27 years behind bars.',
     'Tu libertad de hoy: ninguna dieta.',
     'Your freedom today: no diet.'),
    (74, 74,
     'Mark Twain murió con 74 años, un día después de que el cometa Halley pasara por la Tierra, como había predicho.',
     "Mark Twain died at 74, a day after Halley's comet passed Earth, as he had predicted.",
     'Hoy no mires al cielo: sopla las velas.',
     "Don't look at the sky: blow out the candles."),
    (75, 75,
     'Augusto murió con 75 años preguntando: «¿He interpretado bien mi papel en la comedia de la vida?».',
     'Augustus died at 75 asking: «Have I played my part well in the comedy of life?».',
     'Y todos aplaudieron. Aplaude tú también.',
     'And everyone applauded. You clap too.'),
    (76, 76,
     'Luis XIV murió con 76 años tras 72 de reinado, de gangrena en una pierna.',
     'Louis XIV died at 76 after 72 years on the throne, of gangrene in his leg.',
     '72 años mandando: hoy mandas tú.',
     "72 years in charge: today you're in charge."),
    (76, 76,
     'El cometa Halley vuelve cada 75-76 años: a tu edad, una persona ya ha podido verlo pasar.',
     "Halley's comet returns every 75-76 years: at your age, a person may have seen it pass.",
     '¡Vuelve más que algunas visitas!',
     'It comes back more reliably than some guests!'),
    (77, 77,
     'John Glenn viajó al espacio con 77 años, el astronauta más veterano de la historia.',
     'John Glenn flew to space at 77, the oldest astronaut in history.',
     'De mayor quiero ser astronauta como él.',
     'When I grow up I want to be like him.'),
    (80, 80,
     'Churchill dimitió como primer ministro con 80 años.',
     'Churchill resigned as prime minister at 80.',
     'Dimitió del Gobierno, no de la tarta.',
     'He resigned from office, not from cake.'),
    (81, 81,
     'Benjamin Franklin participó en la redacción de la Constitución de EE. UU. con 81 años.',
     'Benjamin Franklin took part in drafting the US Constitution at 81.',
     'Y tú a los 81 aún puedes con todo.',
     'And at 81 you can still do it all.'),
    (81, 81,
     'La reina Victoria murió con 81 años tras 63 años de reinado.',
     'Queen Victoria died at 81 after 63 years on the throne.',
     '63 años mandando: ¡qué manera de celebrar!',
     '63 years in charge - what a way to celebrate!'),
    (82, 82,
     'Tolstói murió con 82 años en una estación de tren, tras huir de su casa.',
     'Tolstoy died at 82 in a train station, after running away from home.',
     'Hoy no huyas de tu propia fiesta.',
     "Don't run away from your own party today."),
    (82, 82,
     'Goethe murió con 82 años tras terminar la segunda parte de «Fausto».',
     'Goethe died at 82 after finishing the second part of «Faust».',
     'Fausto pactó con el diablo; tú, con la tarta.',
     'Faust made a deal with the devil; you, with the cake.'),
    (83, 83,
     'Thomas Jefferson murió con 83 años, el 4 de julio de 1826, el mismo día que su amigo y rival John Adams.',
     'Thomas Jefferson died at 83, on July 4, 1826, the same day as his friend and rival John Adams.',
     'Qué puntualidad: irse el día de la fiesta nacional.',
     'Talk about timing: leaving on the national holiday.'),
    (83, 83,
     'Víctor Hugo murió con 83 años y su funeral reunió a una multitud en París.',
     'Victor Hugo died at 83 and his funeral drew a huge crowd in Paris.',
     'Miserables, solo los que se pierdan la fiesta.',
     'The only ones miserable are those who miss the party.'),
    (84, 84,
     'Edison murió con 84 años; se conserva un tubo de ensayo que, según Henry Ford, guarda su último aliento.',
     'Edison died at 84; a test tube said to hold his last breath, according to Henry Ford, is preserved.',
     '¡Guarda el aliento para soplar las velas!',
     'Save your breath for blowing out the candles!'),
    (84, 84,
     'Newton murió con 84 años; en su pelo se encontró mercurio, fruto de sus experimentos de alquimia.',
     'Newton died at 84; mercury was found in his hair, from his alchemy experiments.',
     'Todo lo que sube baja... menos tu ánimo.',
     'What goes up must come down - except your spirits.'),
    (85, 85,
     'Con 85 años, Miguel Ángel aún trabajaba como arquitecto jefe de la basílica de San Pedro.',
     "At 85, Michelangelo was still working as chief architect of St. Peter's Basilica.",
     'Nunca es tarde para seguir creando.',
     "It's never too late to keep creating."),
    (86, 86,
     'Monet murió con 86 años, casi ciego por las cataratas, pintando nenúfares hasta el final.',
     'Monet died at 86, almost blind from cataracts, painting water lilies to the end.',
     'Con cataratas y todo, ¡qué vista!',
     'Cataracts and all, what a view!'),
    (87, 87,
     'La Madre Teresa de Calcuta murió con 87 años.',
     'Mother Teresa of Calcutta died at 87.',
     'Un día para cuidarte un poco a ti.',
     'A day to look after yourself a little.'),
    (88, 88,
     'Miguel Ángel murió con 88 años, unos días antes de cumplir 89.',
     'Michelangelo died at 88, a few days before turning 89.',
     'Casi 89: ¡ya empieza la cuenta atrás!',
     'Almost 89 - the countdown begins!'),
    (88, 88,
     'Hokusai murió con 88 años diciendo que con cinco años más habría llegado a ser un verdadero pintor.',
     'Hokusai died at 88, saying that with five more years he could have become a true painter.',
     'Tranquilo: tú tienes todos los años que quieras.',
     'Relax: you have all the years you want.'),
    (90, 90,
     'Con 90 años, Jeanne Calment vendió su piso en usufructo: el comprador murió antes que ella y pagó 30 años de renta.',
     'At 90, Jeanne Calment sold her apartment for a life annuity: the buyer died before her, after paying for 30 years.',
     'Menudo negocio: al final pagó él.',
     'What a deal: he ended up paying for her.'),
    (91, 91,
     'Picasso murió con 91 años en Francia, aún pintando.',
     'Picasso died at 91 in France, still painting.',
     'Ni jubilado ni aburrido.',
     'Never retired, never bored.'),
    (96, 96,
     'Isabel II murió con 96 años tras 70 de reinado.',
     'Elizabeth II died at 96 after 70 years on the throne.',
     'Tú también mereces una corona hoy.',
     'You deserve a crown today too.'),
    (100, 100,
     'Jimmy Carter fue el primer presidente de EE. UU. en cumplir 100 años.',
     'Jimmy Carter was the first US president to turn 100.',
     'Eso sí es aguantar una legislatura.',
     "Now that's outlasting a presidency."),
    (59, 59,
     'Dostoievski murió con 59 años, tras sobrevivir a un simulacro de fusilamiento a los 28.',
     'Dostoevsky died at 59, after surviving a mock execution at 28.',
     'Y tú quejándote del lunes.',
     'And you complain about Mondays.'),
    (61, 61,
     'Hacia los 61 años, Miguel Ángel empezó a pintar «El Juicio Final» en la Capilla Sixtina.',
     'Around 61, Michelangelo started painting «The Last Judgment» in the Sistine Chapel.',
     'Y tú, contento si acierta el Wi-Fi.',
     "And you're happy if the Wi-Fi works."),
    (63, 63,
     'Rembrandt murió con 63 años, arruinado y habiendo enterrado a su mujer y a su hijo.',
     'Rembrandt died at 63, bankrupt and after burying his wife and his son.',
     'Pintó genial, pero de finanzas ni idea.',
     'Great painter, terrible accountant.'),
    (63, 63,
     'Vivaldi murió con 63 años en Viena, en la pobreza, y lo enterraron en una tumba de pobres.',
     "Vivaldi died at 63 in Vienna, penniless, and was buried in a pauper's grave.",
     'Compuso Las Cuatro Estaciones y no pudo pagar ni una.',
     "He wrote The Four Seasons and couldn't afford one."),
    (72, 72,
     'John Wayne, el vaquero más duro de Hollywood, murió con 72 años vencido por el cáncer.',
     "John Wayne, Hollywood's toughest cowboy, died at 72, beaten by cancer.",
     'Hasta el más duro acaba pidiendo silla.',
     'Even the toughest ends up asking for a chair.'),
    (73, 73,
     'Gaudí murió con 73 años atropellado por un tranvía; iba tan desaliñado que los taxis no quisieron llevarlo.',
     'Gaudí died at 73, hit by a tram; he looked so scruffy that taxis refused to take him.',
     'Sagrada Familia sí, pero el look, regular.',
     'Great architect, questionable fashion sense.'),
    (73, 73,
     'Con 73 años, el Coronel Sanders vendió KFC por dos millones de dólares.',
     'At 73, Colonel Sanders sold KFC for two million dollars.',
     'Y tú sin saber ni freír un huevo.',
     "And you can't even fry an egg."),
    (73, 73,
     'Darwin murió con 73 años y lo enterraron en la abadía de Westminster, junto a Newton.',
     'Darwin died at 73 and was buried in Westminster Abbey, next to Newton.',
     'De mono a leyenda, como quien no quiere la cosa.',
     'From monkey to legend, just like that.'),
    (78, 78,
     'Hacia los 78 años, Benjamin Franklin inventó las gafas bifocales.',
     'Around 78, Benjamin Franklin invented bifocal glasses.',
     'Para ver de cerca la tarta y de lejos el gimnasio.',
     'To see the cake up close and the gym far away.'),
    (79, 79,
     'Kant murió con 79 años; cuenta la leyenda que sus vecinos ponían el reloj en hora al verle pasear.',
     'Kant died at 79; legend says his neighbors set their clocks by his daily walk.',
     'Puntual hasta para irse de la fiesta.',
     'Punctual even for leaving the party.'),
    (89, 89,
     'Con 89 años, Clint Eastwood seguía dirigiendo películas, como «El caso Richard Jewell».',
     'At 89, Clint Eastwood was still directing films, like «Richard Jewell».',
     'Y sigue sin sonreír. Una máquina.',
     "And he still doesn't smile. A machine."),
    (92, 92,
     'Con 92 años, David Attenborough narró la serie «Nuestro planeta».',
     'At 92, David Attenborough narrated the series «Our Planet».',
     'Hablar con animales salvajes conserva de maravilla.',
     'Talking to wild animals keeps you young.'),
    (92, 92,
     'Con 92 años, Isabel II vio casarse a su nieto Harry con Meghan Markle.',
     'At 92, Queen Elizabeth II watched her grandson Harry marry Meghan Markle.',
     'Y mantuvo la compostura. Tú no podrías.',
     "And she kept her composure. You couldn't."),
    (94, 94,
     'Con 94 años, David Attenborough consiguió un millón de seguidores en Instagram en menos de cinco horas.',
     'At 94, David Attenborough got a million Instagram followers in under five hours.',
     'Y tú con tres likes de tu madre.',
     "And you've got three likes from your mom."),
    (95, 95,
     'Nelson Mandela murió con 95 años, tras pasar 27 encerrado y llegar a presidente.',
     'Nelson Mandela died at 95, after 27 years in prison and becoming president.',
     'Tú ni aguantas 27 minutos sin móvil.',
     "You can't last 27 minutes without your phone."),
    (95, 95,
     'Stan Lee, el creador de Spider-Man, murió con 95 años.',
     'Stan Lee, the creator of Spider-Man, died at 95.',
     'Con gran cumpleaños viene gran tarta.',
     'With great birthday comes great cake.'),
    (99, 99,
     'Betty White murió con 99 años, diecisiete días antes de cumplir los 100.',
     'Betty White died at 99, seventeen days before turning 100.',
     'Se quedó a nada de la tarta del siglo.',
     'She missed the century cake by a whisker.'),
    (99, 99,
     'El príncipe Felipe murió con 99 años, dos meses antes de cumplir los 100.',
     'Prince Philip died at 99, two months before turning 100.',
     'Llegó a los 99 sin perder el humor ni el protocolo.',
     'He reached 99 without losing his wit or his protocol.'),
    (25, 25,
     'A los 25 años, Maradona marcó con la mano «la mano de Dios» en el Mundial del 86.',
     'At 25, Maradona scored the «Hand of God» goal at the 1986 World Cup.',
     'Dios no miró, pero el árbitro tampoco.',
     "God didn't look, and neither did the referee."),
    (60, 60,
     'Trotski murió con 60 años en México, tras recibir un piolet en la cabeza.',
     'Trotsky died at 60 in Mexico, after being hit in the head with an ice axe.',
     'Hoy el único piolet es el de la tarta de montaña.',
     'Today the only ice axe is for the mountain cake.'),
    (56, 56,
     'Con 56 años, Händel compuso «El Mesías» entero en solo 24 días.',
     'At 56, Handel composed the whole «Messiah» in just 24 days.',
     'Tú tardas 24 días en contestar un WhatsApp.',
     'You take 24 days to answer a text.'),
    (47, 47,
     'Con 47 años, Alexander Fleming descubrió la penicilina al volver de vacaciones y hallar moho en sus placas.',
     'At 47, Alexander Fleming discovered penicillin after returning from holiday to find mold on his dishes.',
     'No limpiar a tiempo salvó millones de vidas.',
     'Not cleaning up on time saved millions of lives.'),
    (39, 39,
     'Emiliano Zapata fue emboscado y asesinado con 39 años en Chinameca.',
     'Emiliano Zapata was ambushed and killed at 39 in Chinameca.',
     'Mejor una emboscada de tarta sorpresa.',
     'Better a surprise cake ambush.'),
    (76, 76,
     'Einstein murió con 76 años y un patólogo le robó el cerebro para estudiarlo.',
     'Einstein died at 76 and a pathologist took his brain to study it.',
     'Menudo cerebro, y tú aún buscas las llaves.',
     'What a brain - and you still lose your keys.'),
    (77, 77,
     'Galileo murió con 77 años; uno de sus dedos se exhibe hoy en un museo de Florencia.',
     'Galileo died at 77; one of his fingers is on display today in a Florence museum.',
     'Y sin embargo se mueve... el dedo, digo.',
     'And yet it moves... the finger, I mean.'),
    (86, 86,
     'Tesla murió con 86 años, solo en una habitación de hotel de Nueva York y casi sin dinero.',
     'Tesla died at 86, alone in a New York hotel room and almost penniless.',
     'Genio, sí; para los negocios, cero.',
     'A genius, sure; at business, zero.'),
    (65, 65,
     'Walt Disney murió con 65 años. El mito de que está congelado es falso: lo incineraron.',
     'Walt Disney died at 65. The myth that he is frozen is false: he was cremated.',
     'Lo único congelado hoy es la tarta de helado.',
     'The only frozen thing today is the ice-cream cake.'),
    (37, 37,
     'Miguel Ángel terminó la Capilla Sixtina con 37 años y la pintó de pie, no tumbado.',
     'Michelangelo finished the Sistine Chapel at 37 and painted it standing up, not lying down.',
     'Y sin un solo tutorial de YouTube.',
     'And without a single YouTube tutorial.'),
    (62, 62,
     'Con 62 años, Tolkien publicó «La Comunidad del Anillo», que empezó como secuela de «El hobbit».',
     'At 62, Tolkien published «The Fellowship of the Ring», which began as a sequel to «The Hobbit».',
     'Mucho camino para un anillo, poco para la tarta.',
     'A long road for a ring, a short one to the cake.'),
    (93, 93,
     'Con 93 años, Isabel II animó al país en plena pandemia con su discurso «volveremos a vernos».',
     'At 93, Queen Elizabeth II cheered up the country in the pandemic with her «we will meet again» speech.',
     'Tú con una semana de confinamiento ya hablabas con la lavadora.',
     'After one week of lockdown you were talking to the washing machine.'),
    (97, 97,
     'Con 97 años, el príncipe Felipe volcó su Land Rover y, pocos días después, lo pillaron conduciendo sin cinturón.',
     'At 97, Prince Philip flipped his Land Rover and, days later, was caught driving without a seat belt.',
     'Un crack: tras el susto, a por otro coche.',
     'A legend: after the crash, straight into another car.'),
]

_COLUMNS = {"es": (2, 4), "en": (3, 5)}  # (fact, joke) column of FACTS per language


def historical_entries(age, language=DEFAULT_LANGUAGE):
    """[(fact, joke)] of the historical facts that apply to the age, in the given language."""
    fact_column, joke_column = _COLUMNS.get(language, _COLUMNS[DEFAULT_LANGUAGE])
    return [(entry[fact_column].replace("{age}", str(age)), entry[joke_column])
            for entry in FACTS if entry[0] <= age <= entry[1]]


def historical_facts(age, language=DEFAULT_LANGUAGE):
    """Facts about people/records at exactly this age (or range of ages)."""
    return [fact for fact, _ in historical_entries(age, language)]


# --- Facts calculated from the exact birth date (or, without it, from the age) ---
# Astronomical constants (days): Earth's orbit 365.2425, Moon's orbit around the Earth (sidereal) 27.3217,
# Martian year 686.98, Mercury's year 87.97, Jupiter's year 4332.59. Earth's orbit is ~940 million km long.
EARTH_ORBIT_KM_MILLIONS = 940
MOON_ORBIT_DAYS = 27.3217
MARS_YEAR_DAYS = 686.98
MERCURY_YEAR_DAYS = 87.97
JUPITER_YEAR_DAYS = 4332.59

# (min_age, {language: template}). Values: {days} {weeks} {months} {hours} {minutes} {seconds} {orbits} {km}
# {moon} {mars} {mercury} {jupiter}
CALCULATED = [
    (1, {"es": "Hoy cumples {days} días de vida.", "en": "Today you turn {days} days old."}),
    (1, {"es": "Has vivido {weeks} semanas completas.", "en": "You've lived {weeks} full weeks."}),
    (1, {"es": "Has cumplido {months} meses.", "en": "You've lived {months} months."}),
    (1, {"es": "Has vivido {hours} horas.", "en": "You've lived {hours} hours."}),
    (1, {"es": "Has vivido {minutes} minutos.", "en": "You've lived {minutes} minutes."}),
    (1, {"es": "Has vivido {seconds} segundos.", "en": "You've lived {seconds} seconds."}),
    (1, {"es": "La Tierra te ha llevado a dar {orbits} vueltas al Sol: unos {km} millones de km recorridos.",
         "en": "Earth has carried you around the Sun {orbits} times: about {km} million km travelled."}),
    (1, {"es": "Desde que naciste, la Luna ha dado {moon} vueltas alrededor de la Tierra.",
         "en": "Since you were born, the Moon has orbited the Earth {moon} times."}),
    (1, {"es": "En Marte tendrías {mars} años, porque allí el año dura 687 días.",
         "en": "On Mars you'd be {mars} years old, since a Martian year lasts 687 days."}),
    (1, {"es": "En Mercurio tendrías {mercury} años: allí el año dura solo 88 días.",
         "en": "On Mercury you'd be {mercury} years old: a year there lasts only 88 days."}),
    (6, {"es": "Desde que naciste, Júpiter ha dado {jupiter} vueltas al Sol.",
         "en": "Since you were born, Jupiter has gone around the Sun {jupiter} times."}),
]


def format_number(number, language, decimals=0):
    """1234567.8 -> '1.234.568' (es) / '1,234,568' (en)"""
    text = f"{number:,.{decimals}f}"
    if language == "es":
        text = text.replace(",", "\x00").replace(".", ",").replace("\x00", ".")
    return text


def life_values(age, language=DEFAULT_LANGUAGE, birth_date=None, today=None):
    """Numbers derived from the exact birth date (or from the age when it isn't given), already formatted."""
    if birth_date is not None and today is not None:
        days = (today - birth_date).days
    else:
        days = round(age * 365.2425)
    number = lambda value, decimals=0: format_number(value, language, decimals)  # noqa: E731
    return {
        "days": number(days), "weeks": number(days // 7), "months": number(age * 12),
        "hours": number(days * 24), "minutes": number(days * 24 * 60), "seconds": number(days * 86400),
        "orbits": number(age), "km": number(age * EARTH_ORBIT_KM_MILLIONS),
        "moon": number(days / MOON_ORBIT_DAYS, 1), "mars": number(days / MARS_YEAR_DAYS, 1),
        "mercury": number(days / MERCURY_YEAR_DAYS), "jupiter": number(days / JUPITER_YEAR_DAYS, 1),
    }


def calculated_facts(age, language=DEFAULT_LANGUAGE, birth_date=None, today=None):
    values = life_values(age, language, birth_date, today)
    return [templates.get(language, templates[DEFAULT_LANGUAGE]).format(**values)
            for minimum, templates in CALCULATED if age >= minimum]


def facts_for_age(age, language=DEFAULT_LANGUAGE, birth_date=None, today=None):
    """Every fact for the age: historical ones followed by the calculated ones."""
    return historical_facts(age, language) + calculated_facts(age, language, birth_date, today)
